CREATE TABLESPACE RT DATAFILE '/u01/app/oracle/oradata/XE/rt.dbf'
SIZE 10M REUSE AUTOEXTEND ON NEXT 2M MAXSIZE 20G;
create user vadya identified by pass DEFAULT TABLESPACE RT
QUOTA 10G ON RT;
grant CREATE SESSION, ALTER SESSION, CREATE TABLE, ALTER ANY TABLE, CREATE TRIGGER to vadya;
